name: I'm Not A Ninja
description: Reverse all the things
meta_description: "I'm Not A Ninja, Reverse all the things"

aboutPage: true

markdown: kramdown
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://imnota.ninja'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://imnota.ninja'
author:         '0xroot'
authorTwitter:  '0xroot'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
